from setuptools import setup, find_packages

setup(
    name="economic-crisis-prediction",
    version="1.0.0",
    author="Your Name",
    author_email="your.email@example.com",
    description="Ensemble ML system for economic recession forecasting",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/economic-crisis-prediction",
    packages=find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    python_requires=">=3.10",
    install_requires=[
        "requests>=2.31.0",
        "pandas>=2.1.0",
        "numpy>=1.24.0",
        "scikit-learn>=1.3.0",
        "xgboost>=2.0.0",
        "tensorflow>=2.14.0",
        "keras>=2.14.0",
        "pyyaml>=6.0",
        "python-dateutil>=2.8.2",
        "tqdm>=4.66.0",
        "matplotlib>=3.8.0",
        "seaborn>=0.13.0",
        "plotly>=5.17.0",
        "scipy>=1.11.0",
        "statsmodels>=0.14.0",
    ],
    entry_points={
        "console_scripts": [
            "align-csv=scripts.align_csv:main",
            "train-recession-model=scripts.recession_prediction_pipeline:main",
        ],
    },
)
